# Site settings
title: SP 800-63 Digital Identity Guidelines Implementation Resources
description: "Resource Center for the NIST Special Publication 800-63 Digital Identity Guidelines"
baseurl: "/800-63-3-Implementation-Resources" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- "*.yml"
- "*/images/*.pdf"

# GitHub information will uncomment ones names are finalized and NIST GitHub Pages resources have been allocated
#org_name: usnistgov
#repo_name: 800-63-ImplResourceCenter

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: /
  collection: false
- text: SP800-63A
  url: /63A/
  collection: 63A
- text: SP800-63B
  url: /63B/
  collection: 63B
- text: SP800-63C
  url: /63C/
  collection: 63C
- text: FAQ
  url: 'https://pages.nist.gov/800-63-FAQ/'
  external: true
  
collections:
  63A:
    output: true
  63B:
    output: true
  63C:
    output: true

#Uncomment when we go live 
host: 0.0.0.0

include:
- _stylesheets
- _javascript

# Custom site configuration
lang: en
